[package]
name = "shuttle-app"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
shuttle-axum = "0.52.0"
shuttle-runtime = "0.52.0"
tokio = { version = "1.28.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11.25"
serde_json = "1.0"
base64 = "0.21"
regex = "1.5"

[[bin]]
name = "shuttle-app"
path = "main.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
